"""empty message

Revision ID: 5609bd977126
Revises: 59b1cd674b8b
Create Date: 2021-11-26 21:58:09.795846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5609bd977126'
down_revision = '59b1cd674b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('banner', sa.String(length=500), nullable=False))
    op.add_column('jobs', sa.Column('banner', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'banner')
    op.drop_column('environments', 'banner')
    # ### end Alembic commands ###
